Layers
shaunclarke2333/terraformVPC pull request #12
Opened 2022-06-07 03:16 UTC by shaunclarke2333

2022-06-07 04:11 UTC, vladimirmukhin requested changes
- Please remove .terraform.lock.hcl - this file is not needed in git
- Pleaase commit level0/terraform.tfstate
- Please create level2 and move ec2 instance from level1 there

2022-06-08 11:45 UTC, vladimirmukhin requested changes

2022-06-08 11:45 UTC, vladimirmukhin commented on level2/backend.tf
> +    key            = "mystate2/terraform.tfstate"
It's better for it to correspond to the name of the local folder i.e. level2/terraform.tfstate.
Same with level1

2022-06-08 11:45 UTC, vladimirmukhin commented on level2/variables.tf
> +}
There is no need to have this as a variable. Instead, you can obtain required information directly from the state.
You can use the following construction for that: https://www.terraform.io/language/state/remote-state-data

2022-06-08 20:09 UTC, shaunclarke2333 commented on level2/backend.tf
> +    key            = "mystate2/terraform.tfstate"
Modfied backend to use matching remote state folders

2022-06-08 20:10 UTC, shaunclarke2333 commented on level2/variables.tf
> +}
Added terraform remote state data source

2022-06-08 23:31 UTC, vladimirmukhin commented on level2/variables.tf
> +
Please fix newlines

2022-06-08 23:31 UTC, vladimirmukhin commented on level1/outputs.tf
> +}
Please add trailing newline

2022-06-08 23:32 UTC, vladimirmukhin approved these changes

2022-06-08 23:35 UTC, shaunclarke2333 commented on level1/outputs.tf
> +}
Added trailing line

2022-06-08 23:35 UTC, shaunclarke2333 commented on level2/variables.tf
> +
removed new line below main.tf

2022-06-08 23:48 UTC, merged